name: CI

on:
  push: 
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        coverage: none   
        tools: composer
    - name: Restore Dependencies
      run: composer update
    - name: Run PHPUnit Tests
      run: vendor/bin/phpunit tests --testdox
    
    
